/**
 * Comic content manifest
 * 
 * This file is auto-generated by scripts/generate-manifest.ts
 * Do not edit manually - regenerate using: npm run generate-manifest
 */

export interface IssueManifest {
  id: string;
  name: string;
  pageCount: number;
  bubbleCount: number;
  audioCount: number;
  hasWebP: boolean;
  hasAudio: boolean;
  hasTimestamps: boolean;
}

export interface BookManifest {
  id: string;
  name: string;
  issues: IssueManifest[];
}

export interface Manifest {
  books: BookManifest[];
  generatedAt: string;
}

export const manifest: Manifest = {
  "books": [
    {
      "id": "tmnt-mmpr-iii",
      "name": "TMNT MMPR III",
      "issues": [
        {
          "id": "issue-1",
          "name": "Issue 1",
          "pageCount": 26,
          "bubbleCount": 214,
          "audioCount": 212,
          "hasWebP": true,
          "hasAudio": true,
          "hasTimestamps": true
        },
        {
          "id": "issue-2",
          "name": "Issue 2",
          "pageCount": 24,
          "bubbleCount": 178,
          "audioCount": 178,
          "hasWebP": true,
          "hasAudio": true,
          "hasTimestamps": true
        }
      ]
    }
  ],
  "generatedAt": "2025-12-01T02:35:45.948Z"
} as const;

export default manifest;
